### ISSUE TITLE
Crash when no result

### ISSUE THREAD

**Issue by KingsDevelopment** [strongloop/loopback-connector-kv-redis#20]
Whenever a where statement  returns 0 results, the app crashes.

	 /project/node_modules/strong-globalize/lib/helper.js:739
	       matched = (name.indexOf(header) === 0);
	                       ^
	 
	 TypeError: name.indexOf is not a function
	     at /project/node_modules/strong-globalize/lib/helper.js:739:23
	     at Array.forEach (native)
	     at headerIncluded (/project/node_modules/strong-globalize/lib/helper.js:737:20)
	     at Object.hashKeys (/project/node_modules/strong-globalize/lib/helper.js:110:12)
	     at formatMessage (/project/node_modules/strong-globalize/lib/globalize.js:96:14)
	     at packMessage (/project/node_modules/strong-globalize/lib/globalize.js:201:17)
	     at Object.rfc5424 (/project/node_modules/strong-globalize/lib/globalize.js:224:10)
	     at StrongGlobalize.log (/project/node_modules/strong-globalize/index.js:185:20)
	     at RedisClient.<anonymous> (/project/node_modules/loopback-connector-redis/lib/redis.js:56:7)
	     at emitOne (events.js:96:13)
	     at RedisClient.emit (events.js:188:7)
	     at RedisClient.on_data (/project/node_modules/redis/index.js:553:14)
	     at Socket.<anonymous> (/project/node_modules/redis/index.js:102:14)
	     at emitOne (events.js:96:13)
	     at Socket.emit (events.js:188:7)
	     at readableAddChunk (_stream_readable.js:176:18)
	     at Socket.Readable.push (_stream_readable.js:134:10)
	     at TCP.onread (net.js:548:20)

using either id, or any other kind of where statement, if the result has no entries, it crashes.

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report

**Comment by superkhau** [comment]
@setogit PTAL

**Comment by netzkind** [comment]
Same result if you connect to a redis-host that is unavailable.
Appearantly this happens when strong-globalize g.log is given the Error-object instead of a string.

**Comment by netzkind** [comment]
probably associated with https://github.com/strongloop-community/loopback-connector-redis/issues/51

**Comment by superkhau** [comment]
@KingsDevelopment Can you verify if @netzkind's fix works for you?

**Comment by jpventura** [comment]
@superkhau, @netzkind Fixed at [loopback-connector-redis](`https://github.com/strongloop-community/loopback-connector-redis/issues/51`). Shouldn't this issue be closed?

**Comment by netzkind** [comment]
@jpventura I'm not sure about that. That project never saw a release of the fixed version, nor a roadmap on when that might happen.
Plus I'm not sure if a fix to loopback-connector-redis helps with loopback-connector-kv-redis.

**Comment by bajtos** [comment]
The stack trace points to `loopback-connector-redis`:

```
     at RedisClient.<anonymous> (/project/node_modules/loopback-connector-redis/lib/redis.js:56:7)
```

I am closing this issue as invalid. Please open a new issue in https://github.com/strongloop-community/loopback-connector-redis if the problem still persists.
